### ISSUE TITLE
Error on running the  php artisan db:seed

### ISSUE THREAD

**Issue by gautham718** [bpocallaghan/laravel-admin-starter#2]
Hi

I am stuck with the following error on running the  php artisan db:seed

  [BadMethodCallException]                                             
  Call to undefined method Illuminate\Database\Query\Builder::roles()

please help me out to resolve the issue

**Comment by bpocallaghan** [comment]
Morning @gautham718 
Will double check quick.
But I think it is the Models/NavigationAdmin.php - missing relationship.

Give me a couple of minutes quick

**Comment by bpocallaghan** [comment]
Hi @gautham718 

Please get the latest [NavigationAdmin](https://github.com/bpocallaghan/laravel-admin-starter/blob/master/app/Models/NavigationAdmin.php)

I am going to download the latest zip and install it to make sure it will work.
Thanks

**Comment by gautham718** [comment]
Yes, It worked. Thanks !!!!

And could you please guide me how to configure that to work in a folder inside document root.

http://localhost/addclarity/

Now the folders are listing when i load that URL and if i load http://localhost/addclarity/public/ then CSS and JS missing

**Comment by bpocallaghan** [comment]
Is it on Windows?
If so, are you using wamp or xampp or something else?

I personally use Windows + wamp

If you want - you can send me a mail to help you out in more detail? bpocallaghan @ gmail

**Comment by gautham718** [comment]
I am on linux (ubuntu 17.04, php 5.6, mysql 5.7 & apache 2.4)

**Comment by bpocallaghan** [comment]
[Setup Virtual Host](https://gist.github.com/bpocallaghan/0aa0bcdcb484cf3ece8ab2d682572141)

The above is for windows - but I think it will push you in the right direction.
I will see if I can find some articles for Linux

**Comment by bpocallaghan** [comment]
@gautham718 

This article seems to cover everything.
You will see some similarities between my gist and this article

[Article](https://www.digitalocean.com/community/tutorials/how-to-set-up-apache-virtual-hosts-on-ubuntu-14-04-lts)

Please shout if you have any questions.
Unfortunately my Linux knowledge is limited.

**Comment by gautham718** [comment]
Thank you so much

**Comment by bpocallaghan** [comment]
My Pleasure.

All this 'virtual host setup' does is to allow you to enter something like 'addclarity.dev' in your browser and not use localhost/addclarity
This makes it easier to define the 'base' url of your website and not have to worry about css / js not loading as you can just go <img src="/images/myimage.png"/> (to always prefix the '/')

However this does have an effect if you will deploy it to a 'sub folder' on a server, for example it will be example.com/folder instead of example.com - If that makes sense.

The other option is to add a 'base' meta in your head in your html [w3schools add base tag](https://www.w3schools.com/tags/tag_base.asp)
This will allow you to add the base url as 'http://localhost/addclarity/public/' And then the css / js should just (just make sure there is no '/' in front of the source.
<img src="/images/myimage.png"/> should become <img src="images/myimage.png"/> when you have the 'base' meta

**Comment by gautham718** [comment]
Hi,
Upon setting the Virtual host for addclarity.com the frontend pages are working fine but, when i load  http://addclarity.com/admin

the following error is thrown

"Oops - unique url, please fix at TitanAdminController::setselectedNavigation()"

But http://addclarity.com/auth/login is working

**Comment by bpocallaghan** [comment]
Awesome - hope you like the virtual host setup - Took me a bit to get used to but very nice!

Okys, That is because it did not find any items in the navigation_admin table.

- Check in your .env file that the `APP_URL=http://addclarity.com`
-  Have a look at the table - navigation_admin - if there are any entries (if not, run php artisan db:seed again)

That should hopefully fix it (basically its not finding any navigation from the database)

If it does not - go to `TitanAdminController::setselectedNavigation()` it will be in /vendor/bpocallaghan/titan/src/controllers
and just do a dd($nav) at around here [NavigationController](https://github.com/bpocallaghan/titan/blob/master/src/Controllers/TitanAdminController.php#L210)

**Comment by gautham718** [comment]
Thanks !! yes, I forgot to change the APP_URL 

Thanks again, and sorry for taking your time

**Comment by bpocallaghan** [comment]
Awesome. Glad its working now. Nope, I am just happy that fellow developers are taking an interest in it.
I hope you like it - please shout when you have any questions - happy to help

**Comment by gautham718** [comment]
Thanks !!

Is it possible to manage the page content from backend now, I couldn't  locate the link for that.

And one more thing, I was not able to log in using the following credentials mentioned in the installation steps.

admin@laravel-admin.com
admin

But this worked 

github@bpocallaghan.co.za
github

**Comment by bpocallaghan** [comment]
Thanks for pointing it out - Updated the readme file.
If you look at /database/seeds/UserTableSeeder.php - The initial users gets created from this file (so you can remove all of them and add one for yourself)

Mmmm. Unfortunately not. 
This is not a full CMS with a website page builder. You can only manage the navigation (all the urls and html title / description of the page) But you will manually have to create the page yourself.

Might be easier to have a look for yourself.
/routes/web.php - At the top of the file you will see all the urls defined for the Website.
They all link to a Controller - most to /app/Http/Controllers/Website/PagesController

I hope that helps. The page builder is in my todo list tho.
If I understand correctly - you might be more interested into something like [Asgard CMS](https://asgardcms.com/)

**Comment by gautham718** [comment]
Thanks
