### ISSUE TITLE
Admin CRUD always acts on FAQ Categories

### ISSUE THREAD

**Issue by informas** [bpocallaghan/laravel-admin-starter#33]
Hi, I am trying to use laravel-admin-starter, in an old 5.4 (dev-Laravel_5.4 Laravel_5.4) because I need to execute under PHP 5.6.4 due to my server limitation.

It run ok, but in admin mode, always it stay on Categories, FAQ Categories. 

I selects on admin menu any option and always apears in breadcrumb, FAQ Categories. For example I selects from menu /admin/general/tags appears thes create Tags form and in the "+ Create" button appears "+ Create Category" if I clicks it, its invokes admin/general/tags/create but when I submits it, the system notifies me that a new **FAQ Category** was created. Yes! FAQ Category, no TAGS!

The same occurs with other options.

It is possible to correct that problem, in this old version?

Can anyone help me?

Do anyone have any suggestion?

TIA

**Comment by informas** [comment]
Hi,

thanks about your response and excuse me for the delay in mi answer...

With your suggests I check .env file and detects that in APP_URL missing the protocol:

APP_URL=larastarter.loc.al

I changes it to:

APP_URL=**http://**larastarter.loc.al

and that solves my problem!

May be? 

I've tried it several times and it seems to be the problem and the solution.

Thanks,

Jorge

**Comment by bpocallaghan** [comment]
Hi Jorge.
No worries, mmm.
Can you perhaps find the file `TitanAdminController` and do a `dd($url)` in that `setSelectedNavigation()` function.
In short, I just want to see what the 'get current url / get url sections' are as it splits the url on the 'slugs' and then tries to find the slugs/path in the database.
So I just want to see what the url is, and then we can see what the issue is (why the slugs do not match)

Please shout if that does not make sense or have some info :)

Feel free to add me on skype if you want "bpocallaghan"

Goodluck
