### ISSUE TITLE
Impersonate Package Still Using App\User

### ISSUE THREAD

**Issue by alhaji-aki** [bpocallaghan/laravel-admin-starter#35]
First and foremost I would like to thank you for this wonderful project.

The impersonate package is using the namespace App\User instead of App\Models\User which results to an error. Kindly check this out and fixx it

**Comment by bpocallaghan** [comment]
Hi @alhaji-aki 
Thank you for giving this project a try.
Which version / tag are you using. Because I did some major refactoring and I actually reversed that change from \App\Models\User back to \App\User.php...

I think branch - version 1 is still using it, let me push a fix for it and then you can see which files changed.
Do you perhaps prefer a fix on the impersonate package, or perhaps a search and replace will do in your project?

As you might've noticed. I am actually busy refactoring version 2 and should hopefully push some updates to it soon (just giving it a try in my current project and making some notes to help with the setup)

**Comment by bpocallaghan** [comment]
[Update](https://github.com/bpocallaghan/laravel-admin-starter/tree/version_1)

I just did a search and replace.
Please let me know if you have any issues or questions.
Thank you,
Happy coding!

**Comment by alhaji-aki** [comment]
Thank you. I have seen your update and I am pulling it. I think the problem is coming from the impersonate package. It is calling App\User instead of Appp\Models\User so in version 2 u can do it such that it uses the config(auth.model) rather.

**Comment by bpocallaghan** [comment]
Thanks, Aaah, good idea, will see what I can do.
I think the update should solve version 1 for now (same namespace path for both)

Please shout if you have trouble or have any questions. Thanks!

**Comment by alhaji-aki** [comment]
You are welcome. And once again thank you for this project
