### ISSUE TITLE
Api problem

### ISSUE THREAD

**Issue by madzat** [bpocallaghan/laravel-admin-starter#36]
Hi , i was testing your project all working fine and after few test i was checking the api and i see is not working so when i try route:list 

> C:\xampp\php\php.exe artisan route:list
"/"
"Whoops. Navigation not found - please see if url is in database (navigation_admin)"

Process finished with exit code 1 at 18:10:41.
Execution time: 1,413 ms.

and if i dump-autoload

> C:\ProgramData\ComposerSetup\bin\composer.bat dump-autoload
Generating optimized autoload files
Warning: Ambiguous class resolution, "App\Events\ActivityWasTriggered" was found in both "C:/xampp/htdocs/app\Events\ActivityWasTriggered.php" and "C:/xampp/htdocs/app\Notifications\ActivityWasTriggered.php", the first will be used.
Warning: Ambiguous class resolution, "App\Events\BaseEvent" was found in both "C:/xampp/htdocs/app\Events\BaseEvent.php" and "C:/xampp/htdocs/app\Notifications\BaseEvent.php", the first will be used.
Warning: Ambiguous class resolution, "App\Events\ContactUsFeedback" was found in both "C:/xampp/htdocs/app\Events\ContactUsFeedback.php" and "C:/xampp/htdocs/app\Notifications\ContactUsFeedback.php", the first will be used.
Warning: Ambiguous class resolution, "App\Events\UserRegistered" was found in both "C:/xampp/htdocs/app\Events\UserRegistered.php" and "C:/xampp/htdocs/app\Notifications\UserRegistered.php", the first will be used.
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover
Discovered Package: nesbot/carbon
Discovered Package: yajra/laravel-datatables-oracle
Discovered Package: spatie/laravel-analytics
Discovered Package: intervention/image
Discovered Package: bpocallaghan/notify
Discovered Package: bpocallaghan/impersonate
Discovered Package: bpocallaghan/alert
Discovered Package: fideloper/proxy
Discovered Package: laravel/tinker
Discovered Package: barryvdh/laravel-ide-helper
Discovered Package: beyondcode/laravel-dump-server
Discovered Package: bpocallaghan/generators
Discovered Package: nunomaduro/collision
Discovered Package: bpocallaghan/titan
Package manifest generated successfully.

Process finished with exit code 0 at 18:12:59.
Execution time: 6,777 ms.
i removed the file BaseEvent, ContactUsFeedback, UserRegistered, ActivityWasTriggered from Notifications and all working fine but i dont know why this file extracted there is problem with php artisan titan:publish --files=app??? normaly as i see from titan folder i mast to see ContactUsSubmitted, UserConfirmedAccount and UserRegistered but is not extracted 

Thanks

**Comment by bpocallaghan** [comment]
Hi @madzat 
Thanks for your interest in the project. Yeah, I think the titan:publish --files=app might be the faulty one.
Honestly the current publish commands are there just to get all the packages files into your project to do changes. I really want to add more specific commands. If I have time today I will add a new one that will publish all the website files (including these events, notifications) due to you will always change all website files (styles, html and php side). As you can see from the commits, this version is very newish and 

I just started with a project and noticed this is needed, due to the project's deadline I just manually copied it from the vendor and changed the namespaces.

Please shout if you have any questions or ideas or issues.
I will let you know once I did some updates to it, thanks a bunch!

**Comment by madzat** [comment]
Hi ,sorry for the late reply i see that now and thanks
and for Feature requests is nice if you give the chance to use avatar or gravatar it will be nice.
Cheers!
