### ISSUE TITLE
Errors: Errors even on installation

### ISSUE THREAD

**Issue by rahulcoresolutions** [bpocallaghan/laravel-admin-starter#41]
Errors on users table seeder:

Migrated:  2018_10_26_034432_alter_users_table (0.25 seconds)
Seeding: UsersTableSeeder

   ErrorException  : Trying to get property 'id' of non-object

  at /Applications/MAMP/htdocs/survey-backend/vendor/bpocallaghan/titan/app/Models/Traits/UserRoles.php:61
    57|     public function attachRole($roleSlug)
    58|     {
    59|         // add dealer role to user
    60|         $role = Role::where('keyword', $roleSlug)->first();
  > 61|         $this->roles()->attach([$role->id]);
    62| 
    63|         return $this->roles;
    64|     }

**Comment by bpocallaghan** [comment]
Hi @rahulcoresolutions 
Sorry about that, I am busy doing some big refactoring / writing unit tests, etc.
Can you try to run `php artisan titan:db:seed` before you do `db:seed` (So that it seed the roles, navigation from the titan package)

Reference [Titan Package](https://github.com/bpocallaghan/titan)

Please let me know if its not working.
Thanks
