### ISSUE TITLE
navigation_admin not found

### ISSUE THREAD

**Issue by milimirstudio** [bpocallaghan/laravel-admin-starter#5]
Hi ,
 http://127.0.0.1:8000  = Works
 http://127.0.0.1:8000/admin =Does not work

display error :
"Whoops. Navigation not found - please see if url is in database (navigation_admin"

thanks 👍

**Comment by bpocallaghan** [comment]
Hi @milimirstudio 

Thanks for giving the project a look.

Just want to confirm - are you using a virtual host - so you can access the site like: http://project.dev instead of the http://127.0.0.1:8000 - This will allow you to have multiple projects on the same pc.

About the error - usually its one of the below:

- Remember to update the url in .env file (APP_URL)
- Remember to run `php artisan db:seed`

Please have a quick look at these closed issues.
[Get ParenstAndYou is Null](https://github.com/bpocallaghan/laravel-admin-starter/issues/1)
[php artisan db:seed error](https://github.com/bpocallaghan/laravel-admin-starter/issues/2)

It might not be relevant to you - just trying to eliminate some common issues :)

Please give me a shout if it did not work or have any questions!! Thanks

**Comment by blissville** [comment]
http://localhost:8000/admin does not work. 
navigation_admin successfully created in the database. 
app_url in .env file points to http://localhost

**Comment by bpocallaghan** [comment]
Hi @blissville 

Just want to check - can you see if there are any entries in the navigation_admin table?

In terms of 'does not work' - do you mean it gives the error 'navigation not found' or 'page not found'

Thanks

**Comment by summermick** [comment]
I got the same issue while using` php artisan serve `to run

**Comment by summermick** [comment]
I figured out the cause...getCurrentUrl() in TitanController in the Titan package does not parse the elegantly. localhost:8000/admin was parsed as /8000/admin instead of /admin.
nice job on your comments.

**Comment by summermick** [comment]
fix your TitanController
` protected function getCurrentUrl($prefix = '/')
    {
        //$url = substr(request()->url(), strlen(config('app.url')));
        // prefix (request can be http://xx and app.url is https)
          $url = request()->path();
          $url = $prefix . ltrim($url, $prefix);
        return $url;
    }`

**Comment by bpocallaghan** [comment]
Hi @summermick 

Thank you for being interested in the 'starter project' and for fixing the issue :) I gave it a few tests and seems to be working 100% - thx.

Titan v0.2.7 has the fix in - [TitanController](https://github.com/bpocallaghan/titan/blob/master/src/Controllers/TitanController.php#L78)

Side note. I am currently busy with a project where I updated this project to Laravel 5.5 and added a few more CRUD (photos, news and events, articles, tenders, etc) and then a simple Page Builder for the website. Hopefully I will get some time - end of this month or early Nov to strip it down and update this repository.

Please shout if you have any questions / suggestions.
Thank you very much!
